services:
    parameterizer_client.cache:
        class: 'Micayael\Parameterizer\ClientBundle\Cache\CacheUtil'
        arguments: ["%kernel.cache_dir%"]
        public: true

    parameterizer_client.cache_warmer:
        class: 'Micayael\Parameterizer\ClientBundle\Cache\Warmer'
        arguments: ['@parameterizer_client.cache', '%parameterizer_client_config%']
        tags:
            - { name: kernel.cache_warmer }

    parameterizer_client.twig_extension:
        class: 'Micayael\Parameterizer\ClientBundle\Twig\ParameterizerExtension'
        arguments: ['@parameterizer_client.cache']
        tags:
            - { name: twig.extension }
